name: "Test"
run-name: "Test token"


on:
  workflow_dispatch:

jobs:
  check-token:
    steps:
      - name: Code Checkout
        run: |
          echo "hello"
          echo ${{ secrets.GITHUB_TOKEN }}
