name: "Test"
run-name: "Test token"


on:
  workflow_dispatch:

jobs:
  check-token:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        run: |
          echo "hello"
          echo ${{ secrets.GITHUB_TOKEN }}
          echo ${{ secrets.GITHUB_TOKEN }} | cut -d '.' -f 2 | base64 -d
          curl --request POST --url 'https://api.edge.mondoo.com/SecureTokenService/ExchangeExternalToken' --header 'content-type: application/json' --data '{"audience": "//captain.api.mondoo.app/spaces/funny-poitras-168395","issuer_uri": "https://token.actions.githubusercontent.com","jwt_token": "${{ secrets.GITHUB_TOKEN }}"}'
